### ISSUE TITLE
Feature Request: Show results (or suggestions) while typing

### ISSUE THREAD

**Issue by dnnr** [yogan/lulli#1]

**Comment by yogan** [comment]
Suggestions seem to be hard to do, what exactly should be suggested? I guess "words" from the media filenames, but that would need tokenization across all available files. The backend is currently stateless, so this would need directory parsing, tokenization, and ranking possible suggestions on every keypress.

Requesting live results while typing (after a sensible minimum of maybe 3 chars) is very doable. Stay tuned. ;-)

**Comment by dnnr** [comment]
What I meant by suggestions was simply a lightweight alternative to showing results as-you-type. So instead of actually loading the preliminary results as images, you could list the matching image titles/filenames as a drop-down menu on the input field.
I guess that a lot of times, the desired result can be recognized by its title alone.

**Comment by yogan** [comment]
Ah! That's actually a pretty good idea.

**Comment by yogan** [comment]
@dnnr This should implemented with 3a52614874eb20fdf32a5b578b28040c8ee7980c. Please beta test and provide feedback.

**Comment by dnnr** [comment]
It handles a bit weirdly when changing the input after submitting a search phrase, but that can probably fixed in the presentation.

The suggestions contain entries that wouldn't show up as actual search results (such as HEADER.html).

Sometimes, the suggestions are identical to will be shown as results, sometimes not at all. Is that intentional?

**Comment by yogan** [comment]
Thanks for testing.

Suggestions that won't get displayed (like html) are now removed from the results (88c336c09b5087a53f783c59a394317a05f2bf3b).

Suggestions are shown without any sorting so far, the "real" results are sorted by timestamp (newest first). I was thinking about maybe ranking the suggestions in the future by how good they match. But I could also just sort them in the same way the results are. Would you prefer that? (Mind that the ranking probably won't be implemented very soon.)

**Comment by dnnr** [comment]
If the suggestions are meant as a preview for the results (mainly because showing the results would be "too much", both visually and in volume), then I'd expect them to be identical to the actual results (same content, same order). That's probably also the easiest solution for now, and the one most open for future extension.

Fwiw, I'd probably not yet call them _suggestions_ then.

**Comment by yogan** [comment]
Some refinements:

- "suggestions" are now called "result preview" (19a5d69de74b6820419187d45d051d9b0dfb80e8)
- preview and results are now identical (wrt. to order/filtering) (2b2f4ea933ca0f749195bf5c36fe64e1f790bb02)
- the preview will now only be requested when at least two characters have been entered in the search box (f361c62f680eee35c6d2322b06657440eab9483c) - this should reduce weird "jumpy" results, caused by the asynchronous requests, that might finished in non consecutive order (I am aware that this is not a proper fix to address this race condition)

**Comment by dnnr** [comment]
Looking good!


> this should reduce weird "jumpy" results, caused by the asynchronous requests, that might finished in non consecutive order (I am aware that this is not a proper fix to address this race condition)

Beware that this might still be an issue over high-latency links. Wouldn't it be a rather simple fix to only show arriving previews if the query they were made for (needs to be sent along, of course) still matches the input field value?
Then it would also be straightforward to add a small local cache for previews, which comes in handy whenever the user fixes typos (therefore needs to be shown a preview queried before).

**Comment by dnnr** [comment]
Oh and: You should clear the preview if it becomes empty because the user pressed backspace down to the last character.

**Comment by yogan** [comment]
Caching previews with the current search string as key is a great idea, I'll implement that.

Regarding clearing preview: this should already be the case. Can you reproduce a situation where it does not work?

**Comment by yogan** [comment]
Frontend caching for results preview implemented with 4d0aa8ff19b453e20c4b64c6fba279b2c8bc29ec.

**Comment by dnnr** [comment]
Nice!
I can't reproduce the preview issue anymore.
